name: Build flutter targets
run-name: Build Parcel for Windows, Linux, and MacOS
on: [push]
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1
      - run: flutter pub get
      - run: flutter build windows
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Parcel_win64
          path: build/windows/x64/runner/Release
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Parcel_linux
          path: build/linux/x64/release/bundle/parcel
  build_mac:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1
      - run: flutter pub get
      - run: flutter build macos
      - run: ditto build/macos/Build/Products/Release/parcel.app build/macos/Build/Products/Release/parcel/parcel.app
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Parcel_macos
          path: build/macos/Build/Products/Release/parcel
